version: 2.1
orbs:
  node: circleci/node@4.0.0
  heroku: circleci/heroku@1.2.2

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: productivity-gateway
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run tests
      
workflows:
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy