version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run tests
      
workflows:
  test:
    jobs:
      - test
      